---
- hosts: localhost
  vars_files:
  - "variables.yml"
  tasks:
  - name: Create Downloads directory
    file:
      path: "{{ ansible_env.HOME }}/Downloads"
      state: directory
  - name: Create repo directory
    file:
      path: "{{ repo_dir }}"
      state: directory
  - include: os_specific/{{ ansible_os_family }}.yml
  - include: tools/fonts.yml
  - include: tools/oh-my-zsh.yml
  - include: tools/fzf.yml
  - include: tools/dotfiles.yml
  - include: tools/vim.yml
  - include: tools/docker.yml
    when: ansible_architecture == "x86_64"