---
- hosts: localhost
  vars:
    repo_dir: "{{ ansible_env.HOME }}/repos"
  tasks:
  - name: Upgrade whole system
    pacman:
      upgrade: yes
    when: ansible_os_family == 'Arch'
  - name: Install git
    pacman:
      name: git
      state: latest
    when: ansible_os_family == 'Arch'
  - name: Create repo directory
    file:
      path: "{{ repo_dir }}"
      state: directory
  - name: Clone dotfiles 
    git:
      repo: https://github.com/furrowb/dotfiles
      dest: "{{ ansible_env.HOME }}/.dotfiles"
      update: yes
  - name: Clone Powerline fonts
    git:
      repo: https://github.com/powerline/fonts
      dest: "{{ repo_dir }}/fonts"
      update: no
  # - name: Install Powerline fonts
  #   shell: "{{ repo_dir }}/fonts/install.sh"
  - name: Sym link vimrc
    file:
      src: "{{ ansible_env.HOME }}/.dotfiles/.vimrc"
      dest: "{{ ansible_env.HOME }}/.vimrc"
      state: link
  - name: Sym link zshrc
    file:
      src: "{{ ansible_env.HOME }}/.dotfiles/.zshrc"
      dest: "{{ ansible_env.HOME }}/.zshrc"
      state: link
  - name: Sym link gitconfig
    file:
      src: "{{ ansible_env.HOME }}/.dotfiles/.gitconfig"
      dest: "{{ ansible_env.HOME }}/.gitconfig"
      state: link