---
- name: Update cache
  pacman:
    update_cache: yes
  become: yes
- name: Upgrade system
  pacman:
    upgrade: yes
  become: yes
- name: Install git
  pacman:
    name: git
    state: latest
  become: yes
- name: Install zsh
  pacman:
    name: zsh
    state: latest
  become: yes
- name: Install vim
  pacman:
    name: vim
    state: latest
  become: yes
- name: Install VSCode
  pacman:
    name: code
    state: latest
  become: yes