---
- name: Clone dotfiles
  git:
    repo: https://github.com/furrowb/dotfiles
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    update: yes
- name: Remove old zshrc file
  file:
    path: "{{ ansible_env.HOME }}/.zshrc.old"
    state: absent
- name: Rename zshrc to zshrc.old
  command: "mv {{ ansible_env.HOME }}/.zshrc {{ ansible_env.HOME }}/.zshrc.old"
  ignore_errors: true
- name: Sym link vimrc
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/.vimrc"
    dest: "{{ ansible_env.HOME }}/.vimrc"
    state: link
- name: Remove old gitconfig file
  file:
    path: "{{ ansible_env.HOME }}/.gitconfig.old"
    state: absent
- name: Rename gitconfig to gitconfig.old
  command: "mv {{ ansible_env.HOME }}/.gitconfig {{ ansible_env.HOME }}/.gitconfig.old"
  ignore_errors: true
- name: Sym link zshrc
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link
- name: Sym link gitconfig
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/.gitconfig"
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    state: link