---
- name: Check if fzf is installed
  command: which fzf
  ignore_errors: yes
  register: check_fzf
- name: Retrieve fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ ansible_env.HOME }}/.fzf"
    update: no
  when: check_fzf.stdout == ""
  register: retrieve_fzf
- name: Install fzf
  command: "{{ ansible_env.HOME }}/.fzf/install --all"
  when: retrieve_fzf.changed